spring:
  application:
    name: api-gateway
server:
  port: 8085
  session:
    cookie:
      name: UISESSION
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  prefix: /api
  routes:
    customer:
      path: /customer/**
      serviceId: customer-service
    account:
      path: /account/**
      serviceId: account-service
security:
  basic:
    enabled: true
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/rest/hello/principal